PROGRAM_NAME = "Transclip"
PROGRAM_AUTHOR = "Jhon Fernandez"
PROGRAM_LICENSE = "GPL-3.0"
PROGRAM_COPYRIGHT = "Copyright 2021 jhondevcode"
PROGRAM_DESCRIPTION = "A small utility to translate clipboard content"
PROGRAM_VERSION = "1.0.0"
PROGRAM_URL = "https://github.com/jhondevcode/transclip-qt"
